### ISSUE TITLE
Listing useful addons

### ISSUE THREAD

**Issue by dereuromark** [drud/awesome-ddev#40]
I wonder if tools like
- https://github.com/ddev/ddev-phpmyadmin

should also be added
Such addons would be quite useful to have listed.

**Comment by rfay** [comment]
I guess I wouldn't think of official add-ons like ddev-phpmyadmin would need to be here since they're in the docs, https://ddev.readthedocs.io/en/stable/users/extend/additional-services/ and in `ddev get --list`. 

However, unofficial add-ons would absolutely be great for a new section.

**Comment by rfay** [comment]
You're welcome to PR nearly anything though :) Closing, use your good judgment.

**Comment by rfay** [comment]
If you think an add-on section (even including offical ones like phpmyadmin) is a good idea, I'm OK with it.

**Comment by tyler36** [comment]
Personally, I would prefer to include the official ones here too. It gives them more exposure which makes them more discoverable.
If you didn't want to maintain the duplication, perhaps a link to the official add-ons docs?

**Comment by dereuromark** [comment]
A link to official doc ones + list of community ones sounds great
