### ISSUE TITLE
Add ddev-vscode-devcontainer-drupal9-template?

### ISSUE THREAD

**Issue by JPustkuchen** [drud/awesome-ddev#8]
If you'd like to, you may add:

DDEV VSCode Drupal Development Container: Start a Drupal VSCode Development Environment in one command: https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template

**Comment by rfay** [comment]
Please just PR it!

**Comment by JPustkuchen** [comment]
Thank you! Sorry you're right, I first wanted to ask, if adding this is an option for you.

Let's proceed here:
https://github.com/drud/awesome-ddev/pull/9
